export enum ErrorEnum {
  // FE Error
  INVALID_TOKEN = "INVALID_TOKEN",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  INVALID_USER = "INVALID_USER",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  INVALID_EMAIL = "INVALID_EMAIL",
  WEBSOCKET_ERROR = "WEBSOCKET_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  // BE Error
  INVALID_PARAMETER = "INVALID_PARAMETER",
  INVALID_REQUEST = "INVALID_REQUEST",
  INVALID_RESPONSE = "INVALID_RESPONSE",
  INVALID_FILE = "INVALID_FILE",
  INVALID_DB = "INVALID_DB",
  // CT(Contract) Error
  INVALID_NETWORK = "INVALID_NETWORK",
  INVALID_ADDRESS = "INVALID_ADDRESS",
}

export type ErrorEnumType = (typeof ErrorEnum)[keyof typeof ErrorEnum];
